DROP TABLE USERS;

CREATE TABLE USERS (
  ID            INT          NOT NULL AUTO_INCREMENT,
  USERNAME      VARCHAR(50)  NOT NULL,
  PASSWORD      VARCHAR(100) NOT NULL,
  SALT          VARCHAR(100) NOT NULL,
  FIRST_NAME    VARCHAR(40)  NOT NULL,
  LAST_NAME     VARCHAR(40)  NOT NULL,
  EMAIL_ADDRESS VARCHAR(100),
  PHONE_NUMBER  VARCHAR(40),
  DATE_CREATED  DATE         NOT NULL,
  LAST_MODIFIED DATE         NOT NULL,
  ACTIVE        BOOLEAN,
  PRIMARY KEY (ID)
);