INSERT INTO USERS (USERNAME, PASSWORD, SALT, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, PHONE_NUMBER, DATE_CREATED, LAST_MODIFIED, ACTIVE)
  VALUES ('STEVEBL', SHA1(
      'DODGYPASSWORD'), 'SALTYSALT', 'Stephen', 'Blance', 'stephen.blance@email.com', '01383 888222', NOW(), NOW(), TRUE);

INSERT INTO USERS (USERNAME, PASSWORD, SALT, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, PHONE_NUMBER, DATE_CREATED, LAST_MODIFIED, ACTIVE)
  VALUES ('BOBBR', SHA1(
      'DODGYPASSWORD'), 'CHEESEBREAD', 'Bob', 'Brown', 'bobby@email.com', NULL, NOW(), NOW(), TRUE);

INSERT INTO USERS (USERNAME, PASSWORD, SALT, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, PHONE_NUMBER, DATE_CREATED, LAST_MODIFIED, ACTIVE)
  VALUES ('TOMTH', SHA1(
      'BADONE'), 'OHDEAR', 'Tom', 'Thumb', 'tommyt@email.com', '01383 999777', NOW(), NOW(), FALSE);

INSERT INTO USERS (USERNAME, PASSWORD, SALT, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, PHONE_NUMBER, DATE_CREATED, LAST_MODIFIED, ACTIVE)
  VALUES ('SALLYST', SHA1(
      'PASSWORD'), 'DOMORE', 'Sally', 'Strong', 'sally.strong@xmail.com', '0171 777111', NOW(), NOW(), TRUE);

INSERT INTO USERS (USERNAME, PASSWORD, SALT, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, PHONE_NUMBER, DATE_CREATED, LAST_MODIFIED, ACTIVE)
  VALUES ('EMMAE', SHA1(
      'EMMAE'), 'MUSH', 'Emma', 'Edwards', 'emmaed@email.com', '0181 111881', NOW(), NOW(), TRUE);

INSERT INTO ROLES (NAME, DATE_CREATED, LAST_MODIFIED)
  VALUE ('USER', NOW(), NOW());

INSERT INTO ROLES (NAME, DATE_CREATED, LAST_MODIFIED)
  VALUE ('ADMINISTRATOR', NOW(), NOW());

INSERT INTO USER_ROLES(USER_ID, ROLE_ID, DATE_CREATED, LAST_MODIFIED)
  SELECT U.ID, R.ID, NOW(), NOW()
  FROM USERS U, ROLES R
  WHERE R.NAME = 'ADMINISTRATOR' AND U.LAST_NAME = 'BLANCE';

INSERT INTO USER_ROLES(USER_ID, ROLE_ID, DATE_CREATED, LAST_MODIFIED)
  SELECT U.ID, R.ID, NOW(), NOW()
  FROM USERS U, ROLES R
  WHERE R.NAME = 'USER' AND U.LAST_NAME IN ('BROWN', 'THUMB', 'STRONG');

COMMIT;