INSERT INTO USERS (USERNAME, PASSWORD, SALT, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, PHONE_NUMBER, DATE_CREATED, LAST_MODIFIED, ACTIVE)
  VALUES ('STEVEBL', SHA1(
      'USERENTEREDPWDSALTYSALT'), 'SALTYSALT', 'Stephen', 'Blance', 'stephen.blance@email.com', '01383 888222', NOW(), NOW(), TRUE);

INSERT INTO USERS (USERNAME, PASSWORD, SALT, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, PHONE_NUMBER, DATE_CREATED, LAST_MODIFIED, ACTIVE)
  VALUES ('BOBBR', SHA1(
      'MOREPWDHERECHEESEBREAD'), 'CHEESEBREAD', 'Bob', 'Brown', 'bobby@email.com', NULL, NOW(), NOW(), TRUE);

INSERT INTO USERS (USERNAME, PASSWORD, SALT, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, PHONE_NUMBER, DATE_CREATED, LAST_MODIFIED, ACTIVE)
  VALUES ('TOMTH', SHA1(
      'MYWIFESNAMEOHDEAR'), 'OHDEAR', 'Tom', 'Thumb', 'tommyt@email.com', '01383 999777', NOW(), NOW(), FALSE);

INSERT INTO USERS (USERNAME, PASSWORD, SALT, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, PHONE_NUMBER, DATE_CREATED, LAST_MODIFIED, ACTIVE)
  VALUES ('SALLYST', SHA1(
      'FOCUSONITDOMORE'), 'DOMORE', 'Sally', 'Strong', 'sally.strong@xmail.com', '0171 777111', NOW(), NOW(), TRUE);

INSERT INTO USERS (USERNAME, PASSWORD, SALT, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, PHONE_NUMBER, DATE_CREATED, LAST_MODIFIED, ACTIVE)
  VALUES ('EMMAE', SHA1(
      'shoesRusMUSH'), 'MUSH', 'Emma', 'Edwards', 'emmaed@email.com', '0181 111881', NOW(), NOW(), TRUE);

COMMIT;